version: '3'
services:
  ai4pa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai4pa-ALL
    volumes:
      - "ai4pa-www:/var/www/"
      - "ai4pa-magento:/root/"
      - "ai4pa-db:/var/lib/mysql/"
    networks:
      - ai4pa-network
    ports:
      - 80:80
      - 8082:8082

volumes:
  ai4pa-www:
  ai4pa-magento:
  ai4pa-db:

networks:
  ai4pa-network:
